let profileCosmetics={};
async function loadProfileCosmetics(){profileCosmetics={};try{const s=await db().collection('cosmetics').get();s.docs.forEach(d=>profileCosmetics[d.id]={id:d.id,...d.data()});}catch(e){}}
const ADMIN_EMAIL='mm2ultimatehub@gmail.com';let profileUser=null,profileData={};const db=()=>window.firebaseDb;
function fallbackName(u){return u.displayName||u.email?.split('@')[0]||'MM2 User'}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function loadProfile(u){profileUser=u;const ref=db().collection('users').doc(u.uid);const snap=await ref.get();profileData=snap.exists?snap.data():{};if(!snap.exists)await ref.set({uid:u.uid,email:u.email||'',username:fallbackName(u),displayName:fallbackName(u),bio:'',avatarUrl:u.photoURL||'',bannerUrl:'',badges:[],createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await loadProfileCosmetics();renderProfile()}
function renderProfile(){const u=profileUser,d=profileData,name=d.username||d.displayName||fallbackName(u);document.getElementById('profileName').textContent=name;document.getElementById('profileEmail').textContent=u.email||'';document.getElementById('profileBio').textContent=d.bio||'Profil məlumatlarını əlavə et.';const av=d.avatarUrl||u.photoURL||'https://ui-avatars.com/api/?name='+encodeURIComponent(name)+'&background=111827&color=fff&size=256';document.getElementById('profileAvatar').src=av;const frame=profileCosmetics[d.equippedCosmetics?.frame];const frameEl=document.getElementById('profileFrame');if(frame?.image){frameEl.src=frame.image;frameEl.classList.remove('hidden')}else frameEl.classList.add('hidden');const banner=document.getElementById('profileBanner');if(d.bannerUrl){banner.src=d.bannerUrl;banner.classList.remove('hidden')}else banner.classList.add('hidden');document.getElementById('profileCoins').textContent=Number(d.coins||0).toLocaleString();const inv=(d.inventory||[]).map(id=>profileCosmetics[id]).filter(Boolean);document.getElementById('profileBadges').innerHTML=inv.filter(x=>x.type==='badge').map(x=>'<span class="profile-badge">✦ '+esc(x.name)+'</span>').join('')+(u.email?.toLowerCase()===ADMIN_EMAIL?'<span class="profile-badge">♛ Admin</span>':'');document.getElementById('profileInventory').innerHTML=inv.map(x=>'<div class="inventory-chip"><img src="'+esc(x.image||'default.svg')+'" alt=""><div class="meta"><strong>'+esc(x.name)+'</strong><small>'+esc(x.type)+'</small></div><a class="store-button owned" href="store.html">Mağaza</a></div>').join('');const safeList=(key)=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}};document.getElementById('statFavorites').textContent=safeList('mm2_favorites').length;document.getElementById('statTrades').textContent=safeList('mm2_trade_history').length;const c=d.createdAt?.toDate?.();document.getElementById('statJoined').textContent=c?c.toLocaleDateString():'—'}
function openEdit(){const d=profileData;document.getElementById('editUsername').value=d.username||fallbackName(profileUser);document.getElementById('editAvatar').value=d.avatarUrl||profileUser.photoURL||'';document.getElementById('editBio').value=d.bio||'';document.getElementById('editBanner').value=d.bannerUrl||'';document.getElementById('profileEdit').classList.add('open')}
async function saveProfile(){const username=document.getElementById('editUsername').value.trim();if(username.length<2)return msg('İstifadəçi adı ən azı 2 simvol olmalıdır.');const data={username,displayName:username,bio:document.getElementById('editBio').value.trim(),avatarUrl:document.getElementById('editAvatar').value.trim(),bannerUrl:document.getElementById('editBanner').value.trim(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};await db().collection('users').doc(profileUser.uid).set(data,{merge:true});profileData={...profileData,...data};document.getElementById('profileEdit').classList.remove('open');renderProfile()}
function msg(t){document.getElementById('profileMessage').textContent=t}
document.addEventListener('DOMContentLoaded',()=>{firebaseAuth.onAuthStateChanged(async u=>{if(!u){location.href='index.html';return}await loadProfile(u)});document.getElementById('editProfile').onclick=openEdit;document.getElementById('cancelProfile').onclick=()=>document.getElementById('profileEdit').classList.remove('open');document.getElementById('saveProfile').onclick=()=>saveProfile().catch(e=>msg(e.message));document.getElementById('logoutProfile').onclick=()=>firebaseAuth.signOut()})